name: CI Workflow

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: Shemnei/reviewdog-action-typos@v0.12.1
        with:
          reporter: github-check
          level: error
          fail_on_error: false
          files: |
            ./src/main/java/com/kCalControl
          locale: en-gb
